In [54]:
import torch

t = torch.tensor(      [[[[4., 9, 2],
                         [5,  6, 2],
                         [2,  4, 5]],
                  
                       [[4., 9, 2],
                         [5,  6, 2],
                         [2,  4, 5]],

                        [[4., 9, 2],
                         [5,  6, 2],
                         [2,  4, 5]]]])


kernel = torch.tensor(   [[[[1., 0, -1],
                         [1,  0, -1],
                         [1,  0, -1]],
                  
                        [[1., 0, -1],
                         [1,  0, -1],
                         [1,  0, -1]],

                        [[1., 0, -1],
                         [1,  0, -1],
                         [1,  0, -1]]]])


#kernel = torch.FloatTensor(1, 3, 3, 3).fill_(15)

'''
for image in t:
    for channel in range(len(image)):
        #print(image[channel])
        for l in range (t.size()[2]):   #строки
             #print(image[channel][l])
             for k in range (t.size()[3]):   #столбцы
                print(image[channel][l][k])
'''
out = torch.FloatTensor(1, 1, 1, 1).zero_()
w = 0
h = 0
kernel_size = 3
stride = 1
# slice 
# w*stride:w*stride + kernel_size   
# 0*1:0*1 + 3 = 0:3 [)
# 1*1:1*1 + 3 = 1:4 [)
# 2*1:2*1 + 3 = 2:5 [)
# h*stride:h*stride + kernel_size
# 0*1:0*1 + 3
#print(t)
#print(t.size()) 
#[из, канал, вниз, вправо]
#k = t[0, 1,1, 1]
k = t[0, 1, 0:3, 0:3]
print(k)
print(kernel)


out[0,0,0,0] = (k*kernel).sum()
print(out)
#ind = torch.tensor([0])
#p = torch.index_select(t[0],0,ind)
#print(p)
 
 
# Every row, only the last column
# print(t[:,2,1:,1:])

tensor([[4., 9., 2.],
        [5., 6., 2.],
        [2., 4., 5.]])
tensor([[[[ 1.,  0., -1.],
          [ 1.,  0., -1.],
          [ 1.,  0., -1.]],

         [[ 1.,  0., -1.],
          [ 1.,  0., -1.],
          [ 1.,  0., -1.]],

         [[ 1.,  0., -1.],
          [ 1.,  0., -1.],
          [ 1.,  0., -1.]]]])
tensor([[[[6.]]]])
